# Generated by Django 4.2.3 on 2023-07-25 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commentapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment", old_name="wrtier", new_name="writer",
        ),
    ]
