# Generated by Django 4.2.3 on 2023-08-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articleapp", "0002_article_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="article", name="like", field=models.IntegerField(default=0),
        ),
    ]
